apiVersion: skaffold/v4beta3 
kind: Config 

build: 
  artifacts:
  #- image: kse-filterkey
  #  context: apps/filterkey
  - image: kse-my-first-streams
    context: apps/my_first_streams

deploy: 
  helm:
    releases:
    - name: kse
      chartPath: helm
      skipBuildDependencies: true
      #setValueTemplates:
      #valueFiles:
      

profiles:
  # my_first_streams 프로파일 참조하여 실행시, parser.yaml을 helm value파일로 쓴다.
  # skaffold dev -p my_first_streams
  - name: my_first_streams
    patches:
      - op: add
        path: /deploy/helm/releases/0/valuesFiles
        value:
          - configs/my_first_streams.yaml
      - op: add
        path: /deploy/helm/releases/0/setValueTemplates
        value:
          # skaffold 기능: 로컬 레지스트리에 방금 build된 이미지의 정보를 불러오기
          # suffix는 build.aritfacs와 맞춰야 한다.
          # 우선순위: cli options > skaffold.yaml > value파일 > default value
          streams.image.registry: '{{ .IMAGE_DOMAIN_kse_my_first_streams }}'
          streams.image.repository: '{{ .IMAGE_REPO_NO_DOMAIN_kse_my_first_streams }}'
          streams.image.tag: '{{ .IMAGE_TAG_kse_my_first_streams }}'

  