# filterkey 예제 설정 
filterkey:
  # 파드 수
  replicas: 2
  image:
    registry: "docker.wai"
    repository: "yunan/log-transformer-streams"
    tag: 0.0.1

  kafka: 
    # KStreams의 처리대상 카프카 설정
    bootstrap-server: "somthing-kafka-headless:9092"
    srcTopic: src-topic

    # 처리 결과가 적재될 토픽 설정
    numPartitions: 8
    sinkTopic: sink-topic
